import streamlit as st

def disclaimer():
    st.write("  ")
    st.write("  ")
    st.divider()
    st.write("Disclaimer: The music provided is generated by a computer algorithm that I have designed. The music output cannot be guaranteed. If you're interested in melody writing and music composition, please consider consulting with your teacher.")
