import streamlit as st
fun_emoji_list = [
    "😂",  "🎉",   "🚀",  "🐱", 
    "🐶",  "🦄",  
    "🎶",  "😱","👼🏻","💃🏻","🐰","🐒","🐣","🦀","💥","✨","🥳",
    "🍦",  "🌟",  "👻",  
    "🎈",   "🎮",  "💩"
]
import random
def rain_emoji():
    emo=random.choice(fun_emoji_list)
    st.balloons()
    rain(emo,animation_length=1)

def disclaimer():
    st.write("  ")
    st.write("  ")
    st.divider()
    st.write("Disclaimer: The music provided is generated by a computer algorithm that I designed. The music output cannot be guaranteed. If you're interested in melody writing and music composition, please consider consulting with your teacher.")
    

button_style = """
<style>
a.button {
    display: inline-block;
    padding: 4px 20px;
    font-size: 16px;
    color: white;
    background-color: #4CAF50;
    text-align: center;
    text-decoration: none;
    border-radius: 8px;
    border: 2px solid #4CAF50;
    transition: background-color 0.3s, border-color 0.3s;
    margin-top: 1px; /* Adjust this value to move the button closer to the top */
}

a.button:hover {
    background-color: #45a049;
    border-color: #45a049;
}
</style>
"""
